create table TRACKNOT(
TRACKID NUMBER PRIMARY KEY NOT NULL,
TRACK_NAME VARCHAR2(30) NOT NULL
);

create table EXAMPLE
(
EX_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
FAVE_SONG_ID NUMBER,
CONSTRAINT FK_FAVESONG FOREIGN KEY (FAVE_SONG_ID)
REFERENCES TRACKNOT(TRACKID)
);

CREATE SEQUENCE EX_ID_SEQ
INCREMENT BY 1
START WITH 1;


--TRIGGER
CREATE OR REPLACE TRIGGER EX_ID_TRIGGER
BEFORE INSERT ON EXAMPLE
FOR EACH ROW
BEGIN
  IF :NEW.EX_ID IS NULL THEN
    SELECT EX_ID_SEQ.NEXTVAL INTO :new.EX_ID FROM DUAL;
  END IF;
END;

/

select * from DUAL;

SELECT * FROM EXAMPLE;

insert into TRACKNOT(TRACKID,TRACK_NAME)
values(2,'track');

INSERT INTO EXAMPLE(EX_ID, FIRSTNAME, LASTNAME, FAVE_SONG_ID)
VALUES(ex_id_SEQ.nextval, 'Genesis','Bondss', 1);

Insert into example(EX_ID, FIRSTNAME, LASTNAME, fave_song_ID)
values(ex_id_seq.nextval, 'test', 'testing', 2);

select * from USERS;
