
-- 4.1 BASIC STORED PROCEDURE --
-- Create a stored procedure that selects the first and last names of all the employees.
CREATE OR REPLACE PROCEDURE
EMP_NAMES (FNAME OUT VARCHAR2, LNAME OUT VARCHAR2)
AS 
BEGIN
  SELECT FIRSTNAME INTO FNAME FROM EMPLOYEE;
  SELECT LASTNAME INTO LNAME FROM EMPLOYEE;
END EMP_NAMES;
/


-- 4.2 STORED PROCEDURE INPUT PARAMETERS --
-- Create a stored procedure that updates the personal information of an employee.
CREATE OR REPLACE PROCEDURE
UPDATE_EMP_NAME (EMPID IN NUMBER, FNAME IN VARCHAR2, LNAME IN VARCHAR2)
AS
BEGIN
  UPDATE EMPLOYEE 
  SET FIRSTNAME = FNAME, LASTNAME = LNAME
  WHERE EMPLOYEEID = EMPID;
END UPDATE_EMP_NAME;
/

-- Create a stored procedure that returns the managers of an employee.
CREATE OR REPLACE PROCEDURE
GET_MANAGER (EMPID IN NUMBER, MANS OUT NUMBER)
AS
BEGIN
  SELECT REPORTSTO INTO MANS FROM EMPLOYEE
  WHERE EMPLOYEEID = EMPID;
END GET_MANAGER;


-- 4.3 STORED PROCEDURE OUTPUT PARAMETERS --
-- Create a stored procedure that returns the name and company of a customer.
CREATE OR REPLACE PROCEDURE
GET_NAME_AND_COMPANY (CUSTID IN NUMBER, NAME OUT VARCHAR2, COMP OUT VARCHAR2)
AS
BEGIN
  SELECT CONCAT(FIRSTNAME, CONCAT(' ', LASTNAME)) INTO NAME FROM CUSTOMER;
  SELECT COMPANY INTO COMP FROM CUSTOMER;
END GET_NAME_AND_COMPANY;
/
