
CREATE SEQUENCE USERID_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE REQUESTID_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE OR REPLACE TRIGGER USERID_TRIG
AFTER INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.USERID IS NULL THEN
    SELECT USERID_SEQ.NEXTVAL INTO :NEW.USERID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER REQUESTID_TRIG
AFTER INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.REQUESTID IS NULL THEN
    SELECT REQUESTID_SEQ.NEXTVAL INTO :NEW.REQUESTID FROM DUAL;
  END IF;
END;
/
