INSERT INTO "EMPLOYEE" (ID, FIRST_NAME, LAST_NAME) VALUES(1,'Matt','Prass');
INSERT INTO "EMPLOYEE" (ID, FIRST_NAME, LAST_NAME) VALUES(2,'Joe','Smith');
INSERT INTO "EMPLOYEE" (ID, FIRST_NAME, LAST_NAME) VALUES(3,'John','Smith');