
-- 3.1 SYSTEM DEFINED FUNCTIONS --

-- Create a function that returns the current time.
CREATE OR REPLACE FUNCTION TIME_NOW 
RETURN TIMESTAMP AS NOW TIMESTAMP;
BEGIN
  RETURN CURRENT_TIMESTAMP;
END;
/
SELECT TIME_NOW FROM DUAL;

-- Create a function that returns the length
-- of a mediatype from the mediatype table
CREATE OR REPLACE FUNCTION MEDIATYPE_LEN (TYPEID NUMBER)
RETURN NUMBER AS LEN NUMBER;
BEGIN
  SELECT LENGTH(NAME) INTO LEN FROM MEDIATYPE
  WHERE MEDIATYPEID = TYPEID;
  RETURN LEN;
END;
/
SELECT MEDIATYPE_LEN(2) FROM DUAL;


-- 3.2 SYSTEM DEFINED AGGREGATE FUNCTIONS --

-- Create a function that returns the average total of all invoices
CREATE OR REPLACE FUNCTION AVG_TOTAL
RETURN NUMBER AS AVG_TOTAL NUMBER;
BEGIN
  SELECT AVG(TOTAL) INTO AVG_TOTAL FROM INVOICE;
  RETURN AVG_TOTAL;
END;
/
SELECT AVG_TOTAL FROM DUAL;

-- Create a function that returns the most expensive track
CREATE OR REPLACE FUNCTION MOST_EXP_TRACK
RETURN VARCHAR2 AS MAX_TRACK VARCHAR2;
BEGIN
  SELECT NAME INTO MAX_TRACK FROM TRACK
  WHERE UNITPRICE = (SELECT MAX(UNITPRICE) FROM TRACK);
  RETURN MAX_TRACK;
END;
/


-- 3.3 USER DEFINED SCALAR FUNCTIONS --

-- Create a function that returns the average price
-- of invoiceline items in the invoiceline table
CREATE OR REPLACE FUNCTION AVG_PRICE_LINE
RETURN NUMBER AS AVG_PRICE_LINE NUMBER;
BEGIN
  SELECT AVG(UNITPRICE) INTO AVG_PRICE_LINE FROM INVOICELINE;
  RETURN AVG_PRICE_LINE;
END;
/
SELECT AVG_PRICE_LINE FROM DUAL;


-- 3.4 USER DEFINED TABLE VALUED FUNCTIONS --

-- Create a function that returns all employees who are born after 1968.
CREATE OR REPLACE FUNCTION BORN_AFTER_1968
RETURN SYS_REFCURSOR AS CUR SYS_REFCURSOR;
BEGIN
  OPEN CUR FOR
  SELECT * FROM EMPLOYEE
  WHERE BIRTHDATE >= TO_DATE('01-01-1968', 'MM-DD-YYYY');
  RETURN CUR;
END;
/
SELECT BORN_AFTER_1968 FROM DUAL;
