CREATE USER MyDatabase
IDENTIFIED BY p4ssw0rd;

GRANT CONNECT TO MyDatabase;
GRANT RESOURCE TO MyDatabase;
GRANT CREATE SESSION TO MyDatabase;
GRANT CREATE TABLE TO MyDatabase;
GRANT CREATE VIEW TO MyDatabase;