CREATE TABLE EXAMPLE
(
EX_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
FAVORITE_SONG_ID NUMBER,
CONSTRAINT FK_FAVSONG FOREIGN KEY (FAVORITE_SONG_ID)
REFERENCES TRACK(TRACKID)
);

--SEQUENCE
CREATE SEQUENCE EX_ID_SEQ
INCREMENT BY 1
START WITH 1;

--TRIGGER
CREATE OR REPLACE TRIGGER EX_ID_TRIGGER
BEFORE INSERT ON EXAMPLE
FOR EACH ROW
BEGIN
  IF :NEW.EX_ID IS NULL THEN
    SELECT EX_ID_SEQ.NEXTVAL INTO :NEW.EX_ID FROM DUAL;
    END IF;
END;
/

INSERT INTO EXAMPLE(FIRSTNAME, LASTNAME, FAVORITE_SONG_ID)
VALUES('Daniel', 'Fairbanks', 22);

INSERT INTO EXAMPLE(EX_ID, FIRSTNAME, LASTNAME, FAVORITE_SONG_ID)
VALUES(EX_ID_SEQ.NEXTVAL, 'Andrew', 'Fairbanks', 105);

SELECT * FROM EXAMPLE;

UPDATE EXAMPLE
SET FIRSTNAME = 'Andrew'
WHERE EX_ID = 1;

DELETE FROM EXAMPLE
WHERE EX_ID = 2;

