--ORDER BY
SELECT * FROM Album ORDER BY Title;

--GROUP BY
SELECT COUNT(CustomerID), Country FROM Customer GROUP BY Country;

--WHERE
SELECT * FROM Album WHERE ArtistID = 19;

--HAVING
SELECT COUNT(CustomerID), Country FROM Customer GROUP BY Country HAVING COUNT(CustomerID) > 5;

--UNION
SELECT City FROM Customer UNION SELECT City FROM EMPLOYEE ORDER BY City;

--EXISTS

--LIKE/WILDCARDS

--AGGREGATE FUNCS (3)

--SCALAR FUNCS (3)

--NESTED QUERY (1)