package com.question.nine;

import java.util.ArrayList;


/**
 * Create an ArrayList which stores numbers from 1 to 100 and
 * prints out all the prime numbers to the console.
 * 
 * @author Katie
 */
public class PrimeNums {

	/**
	 * Stores all the numbers from 0 to max in an array
	 * @param max
	 * 		The value of ints to go up to
	 * @return
	 * 		The ArrayList of integer  values
	 */
	public static ArrayList<Integer> storeNums(int max){
		ArrayList<Integer> themNums = new ArrayList<Integer>();
		for(int i=0;i<max;i++) {
			themNums.add(i);
		}
		return themNums;
	}
	
	/**
	 * Get an ArrayList containing all of the prime nums from the ArrayList typically generated by storeNums
	 * @param searchList
	 * 		the ArrayList of ints to search for prime nums in
	 * @return
	 * 		The array containing the prime nums
	 */
	public static ArrayList<Integer> primeNums(ArrayList<Integer> searchList){
		
		ArrayList<Integer> themPrimes = new ArrayList<Integer>();
		for(int i=0;i<searchList.size();i++) {
			if(isPrime(searchList.get(i))) {
				//System.out.println(i);
				themPrimes.add(i);
			}
			
		}
		return themPrimes;
	}
	
	/**
	 * General for printing an array out nicely
	 * @param toPrint
	 * 		The array to print
	 */
	public static void printArray(ArrayList<Integer> toPrint) {
		for(int i=0;i<toPrint.size();i++) {
			System.out.print(toPrint.get(i)+" ");
		}
	}
	
	/**
	 * Checks if a number is prime
	 * @param checkNum
	 * 		The number to check
	 * @return
	 * 		Boolean indicating whether or not the number is prime
	 */
	public static boolean isPrime(int checkNum) {
	    if (checkNum%2==0) return false;
	    for(int i=3;i*i<=checkNum;i+=2) {
	        if(checkNum%i==0)
	            return false;
	    }
	    return true;
	}

	
}
