
CREATE OR REPLACE FUNCTION GET_BALANCE (ID NUMBER)
RETURN NUMBER AS BAL NUMBER;
BEGIN
  SELECT BALANCE INTO BAL FROM ACCOUNT WHERE ACCOUNTID = ID;
  RETURN BAL;
END;
/

SELECT GET_BALANCE(1001) FROM DUAL;

SELECT * FROM ACCOUNT
WHERE USERID = 3;
