-- Data Manipulation

UPDATE USERS SET FIRSTNAME = 'Randall' WHERE USERID = 7;

CREATE OR REPLACE PROCEDURE ADD_USER
(FIRST VARCHAR2, LAST VARCHAR2, EM VARCHAR2, PASS VARCHAR2)
AS
BEGIN
  INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORD)
  VALUES (FIRST, LAST, EM, PASS);
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_FIRST_NAME (ID NUMBER, NAME VARCHAR2)
AS
BEGIN
  UPDATE USERS
  SET FIRSTNAME = NAME
  WHERE USERID = ID;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_LAST_NAME (ID NUMBER, NAME VARCHAR2)
AS
BEGIN
  UPDATE USERS
  SET LASTNAME = NAME
  WHERE USERID = ID;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_PASSWORD (ID NUMBER, PW VARCHAR2)
AS
BEGIN
  UPDATE USERS
  SET PASSWORD = PW
  WHERE USERID = ID;
END;
/

CREATE OR REPLACE PROCEDURE DEACTIVATE_ACCOUNT (ID NUMBER)
AS
BEGIN
  UPDATE ACCOUNT
  SET ACTIVE = 'N'
  WHERE ACCOUNTID = ID;
END;
/

CREATE OR REPLACE PROCEDURE WITHDRAW (AMOUNT NUMBER, ID NUMBER)
AS
BEGIN
  UPDATE ACCOUNT
  SET BALANCE = BALANCE - AMOUNT
  WHERE ACCOUNTID = ID;
END;
/

CREATE OR REPLACE PROCEDURE DEPOSIT (AMOUNT NUMBER, ID NUMBER)
AS
BEGIN
  UPDATE ACCOUNT
  SET BALANCE = BALANCE + AMOUNT
  WHERE ACCOUNTID = ID;
END;
/

