Create table example
(
EX_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
FAVE_SONG_ID NUMBER,
CONSTRAINT FK_FAVESONG FOREIGN KEY (FAVE_SONG_ID)
REFERENCES TRACK(TRACKID)
);

CREATE SEQUENCE EX_ID_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO EXAMPLE (EX_ID, FIRSTNAME, LASTNAME, FAVE_SONG_ID)
VALUES (0, 'Genisis', 'Bonds', 17);

CREATE OR REPLACE TRIGGER EX_ID_TRIGGER
BEFORE INSERT ON EXAMPLE
FOR EACH ROW
BEGIN
  if :new.ex_id is null then
    select ex_id_seq.nextval into :new.ex_id from dual;
  end if;
END;
/

commit;
