-- Order By
SELECT * FROM CUSTOMER
ORDER BY LASTNAME, FIRSTNAME;

-- Group By
SELECT T2.NAME, COUNT(*)
FROM TRACK T1, GENRE T2
WHERE T1.GENREID = T2.GENREID
GROUP BY T2.NAME;

-- Having
SELECT T2.NAME, COUNT(*)
FROM TRACK T1, GENRE T2
WHERE T1.GENREID = T2.GENREID
GROUP BY T2.NAME
HAVING T2.NAME = 'Jazz';

-- Where
SELECT TITLE
FROM ALBUM T1, ARTIST T2
WHERE T1.ARTISTID = T2.ARTISTID
AND T2.NAME = 'AC/DC';

-- Union
SELECT 'Customer', FIRSTNAME, LASTNAME, CITY, COUNTRY, PHONE
FROM CUSTOMER
UNION
SELECT 'Employee', FIRSTNAME, LASTNAME, CITY, COUNTRY, PHONE
FROM EMPLOYEE;
  
-- Exists
SELECT TITLE
FROM ALBUM
WHERE EXISTS (SELECT ARTISTID FROM ARTIST 
              WHERE ARTISTID = ALBUM.ARTISTID
              AND NAME = 'AC/DC');
              
-- Like / Wildcards
SELECT FIRSTNAME, LASTNAME
FROM EMPLOYEE
WHERE LASTNAME LIKE 'J%'
AND CITY LIKE 'C_l%';

-- 3 Aggregate Functions
SELECT SUM(UNITPRICE) FROM INVOICELINE;
SELECT COUNT(*) FROM INVOICELINE;
SELECT AVG(UNITPRICE) FROM INVOICELINE;

-- 3 Scaler Functions
SELECT FIRSTNAME, LENGTH(FIRSTNAME) AS "First Name Length"
FROM CUSTOMER;

select * from customer
where upper(firstname) like 'A%';

select upper(firstname) from customer;
select lower(lastname) from employee;

-- Nested Query
SELECT TITLE FROM ALBUM
WHERE ARTISTID IN (SELECT ARTISTID FROM ARTIST WHERE NAME = 'AC/DC');






