CREATE USER db4_user
IDENTIFIED BY uDaE4NXz8tJjkEzY;

GRANT CONNECT TO db4_user;
GRANT RESOURCE TO db4_user;
GRANT CREATE SESSION TO db4_user;
GRANT CREATE TABLE TO db4_user;
GRANT CREATE VIEW TO db4_user;