CREATE VIEW tracklist AS
SELECT * FROM TRACK WHERE LOWER(NAME) LIKE '% for %';

SELECT * FROM TRACKLIST;

CREATE VIEW albumlist AS
SELECT * FROM ALBUM WHERE ALBUMID BETWEEN 250 AND 350;

SELECT * FROM ALBUMLIST;

SELECT t.NAME as trackname, a.TITLE as "Album Title" 
FROM TRACKLIST t INNER JOIN ALBUMLIST a
ON t.ALBUMID = a.ALBUMID;

SELECT t.NAME as trackname, a.TITLE as "Album Title" 
FROM TRACKLIST t FULL OUTER JOIN ALBUMLIST a
ON t.ALBUMID = a.ALBUMID;

SELECT t.NAME as trackname, a.TITLE as "Album Title" 
FROM TRACKLIST t FULL OUTER JOIN ALBUMLIST a
ON t.ALBUMID = a.ALBUMID
WHERE t.ALBUMID IS NULL OR a.ALBUMID IS NULL;

SELECT t.NAME as trackname, a.TITLE as "Album Title" 
FROM TRACKLIST t RIGHT OUTER JOIN ALBUMLIST a
ON t.ALBUMID = a.ALBUMID;

SELECT t.NAME as trackname, a.TITLE as "Album Title" 
FROM TRACKLIST t LEFT OUTER JOIN ALBUMLIST a
ON t.ALBUMID = a.ALBUMID;

SELECT tr.NAME as trackname, al.TITLE as "Album Title", ar.ARTISTID 
FROM TRACK tr 
INNER JOIN ALBUM al
ON tr.ALBUMID = al.ALBUMID
INNER JOIN ARTIST ar 
ON ar.ARTISTID = al.ARTISTID;

SELECT PLAYLIST.PLAYLISTID, PLAYLISTTRACK.PLAYLISTID, MEDIATYPE.MEDIATYPEID,
GENRE.GENREID, INVOICELINE.INVOICELINEID, INVOICE.INVOICEID, TRACK.TRACKID, 
CUSTOMER.CUSTOMERID, EMPLOYEE.EMPLOYEEID, ALBUM.TITLE, ARTIST.ARTISTID 
FROM TRACK 
INNER JOIN ALBUM ON TRACK.ALBUMID = ALBUM.ALBUMID
INNER JOIN ARTIST ON ARTIST.ARTISTID = ALBUM.ARTISTID
INNER JOIN PLAYLISTTRACK ON PLAYLISTTRACK.TRACKID = TRACK.TRACKID
INNER JOIN PLAYLIST ON PLAYLIST.PLAYLISTID = PLAYLISTTRACK.PLAYLISTID
INNER JOIN MEDIATYPE ON MEDIATYPE.MEDIATYPEID = TRACK.MEDIATYPEID
INNER JOIN GENRE ON GENRE.GENREID = TRACK.GENREID
INNER JOIN INVOICELINE ON INVOICELINE.TRACKID = TRACK.TRACKID
INNER JOIN INVOICE ON INVOICE.INVOICEID = INVOICELINE.INVOICEID
INNER JOIN CUSTOMER ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
INNER JOIN EMPLOYEE ON EMPLOYEE.EMPLOYEEID = CUSTOMER.SUPPORTREPID
INNER JOIN EXAMPLE ON EXAMPLE.FAV_SONG_ID = TRACK.TRACKID;



