create table EXAMPLE
(
EX_ID number primary key,
FIRSTNAME varchar2(30) not null,
LASTNAME varchar2(30) not null,
FAV_SONG_ID number,

CONSTRAINT FK_FAV_SONG FOREIGN KEY (FAV_SONG_ID)
REFERENCES TRACK(TRACKID)
);

-- SEQUENCE
create SEQUENCE EX_ID_SEQ
INCREMENT BY 1
START WITH 1;

-- TRIGGER
CREATE OR REPLACE TRIGGER EX_ID_TRIGGER
BEFORE INSERT ON EXAMPLE
FOR EACH ROW
BEGIN
  IF :NEW.EX_ID IS NULL THEN
    SELECT EX_ID_SEQ.NEXTVAL INTO :NEW.EX_ID FROM DUAL;
  END IF;  
END;
/


INSERT INTO EXAMPLE(FIRSTNAME, LASTNAME, FAV_SONG_ID)
VALUES('test', 'tester', 105);

UPDATE EXAMPLE
SET FIRSTNAME = 'Andrew'
WHERE EX_ID = 0;

DELETE FROM EXAMPLE
WHERE EX_ID = 1;

COMMIT;

ROLLBACK;

SELECT * FROM EXAMPLE;