
--DROP USER reimb;
CREATE USER reimb IDENTIFIED BY somberlain;
GRANT CONNECT TO reimb;
GRANT RESOURCE TO reimb;
GRANT CREATE SESSION TO reimb;
GRANT CREATE TABLE TO reimb;
GRANT CREATE VIEW TO reimb;
