CREATE TABLE example (
  EX_ID NUMBER PRIMARY KEY,
  FIRST_NAME VARCHAR2(30) NOT NULL,
  LAST_NAME VARCHAR2(30) NOT NULL,
  FAVORITE_SONG_ID NUMBER,
    CONSTRAINT FK_FAVESONG FOREIGN KEY (FAVORITE_SONG_ID)
    REFERENCES TRACK(TRACKID)
);

-- SEQUENCE
CREATE SEQUENCE EX_ID_SEQ
  INCREMENT BY 1 START WITH 1;

-- TRIGGER OR PROCEDURE
CREATE OR REPLACE TRIGGER EX_ID_TRIGGER
  BEFORE INSERT ON example
  FOR EACH ROW
  BEGIN
    IF :new.ex_id IS NULL THEN
      SELECT ex_id_seq.NEXTVAL INTO :new.ex_id FROM DUAL;
    END IF;
  END;

/

SELECT * FROM example;

INSERT INTO example(EX_ID, FIRST_NAME, LAST_NAME, FAVORITE_SONG_ID)
  values(EX_ID_SEQ.nextval, 'David', 'Smith', 42);

INSERT INTO example(FIRST_NAME, LAST_NAME, FAVORITE_SONG_ID)
  values('test', 'testing', 42*2);

SELECT * FROM example;

UPDATE example
  SET first_name = 'Andrew'
  WHERE ex_id = 1;

DELETE FROM example where first_name = 'test';

COMMIT;
