-- Order playlists with more than 10 tracks by number of songs
SELECT COUNT(TRACKID) AS NUM_TRACKS, PLAYLISTID FROM PLAYLISTTRACK
GROUP BY PLAYLISTID
HAVING COUNT(TRACKID) > 20
ORDER BY NUM_TRACKS DESC;

-- Get all audio tracks longer than 8 minutes
SELECT MILLISECONDS, NAME, ALBUM.TITLE AS ALBUM, COMPOSER FROM TRACK
LEFT JOIN ALBUM ON ALBUM.ALBUMID = TRACK.ALBUMID
WHERE MEDIATYPEID <> 3 AND MILLISECONDS > (8 * 60 * 1000)
ORDER BY MILLISECONDS DESC;

-- Gets all the albums which start with "The _o"
SELECT TITLE, ARTIST.NAME AS ARTIST FROM ALBUM
LEFT JOIN ARTIST ON ARTIST.ARTISTID = ALBUM.ARTISTID
WHERE UPPER(TITLE) LIKE 'THE _O%'
ORDER BY ARTIST, TITLE;

SELECT TITLE, ARTIST.NAME AS ARTIST FROM ALBUM
LEFT JOIN ARTIST ON ARTIST.ARTISTID = ALBUM.ARTISTID
WHERE SUBSTR(TITLE, 0, 4) NOT LIKE 'THE %'
ORDER BY ARTIST, TITLE;

SELECT NAME, UNITPRICE FROM TRACK
WHERE EXISTS (SELECT NAME FROM TRACK WHERE UNITPRICE < 1.0);
